### ISSUE TITLE
Manage Labels and Label Assignment using Groups

### ISSUE THREAD

**Issue by kgpayne** [meltano/.github#13]
Until we are willing to invest in adopting Pulumi to manage GitHub labels (and more), it may be easier to further augment the label-sync action in this repo to support label groups and repo selection.

```yaml
label-groups:
  core:
  - name: "label name"
    description: "label description"
    color: "0075CA" #hex color
    aliases:
    - "other labels to rename"
  singer-ecosystem:
  - name: "SDK Feature Candidate"
    description: "Applied to PR's and issues that may be precursors to SDK functionality."
    color: "0075CA" #hex color
    aliases:
    - "other labels to rename"

repo-labels:
- name: Core Labels
  label-groups:
  - core
  patterns:
  - "meltano/*"
  - "MeltanoLabs/*"
- name: Singer Ecosystem Labels
  label-groups:
  - singer-ecosystem
  patterns:
  - "meltano/sdk"
  - "MeltanoLabs/*"
```
